Rules:
    HttpHeaderXSSProtectionPresent:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ["setName", ["HttpHeaderXSSProtection"]]
            - ["setHeaderToSearchFor", ["X-XSS-Protection"]]

    HttpHeaderXSSProtectionSecure:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderXSSProtection"]]
            - ["setHeaderToSearchFor", ["X-XSS-Protection"]]
            - ["setValue", ["1; mode=block"]]

    HttpHeaderExposeLanguage:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderNotPresent
        calls:
            - ["setName", ["HttpHeaderExposeLanguage"]]
            - ["setHeaderToSearchFor", ["X-Powered-By"]]

    HttpRequestTime:
        class: \Frickelbruder\KickOff\Rules\HttpRequestTime

    HttpHeaderHasFarFutureExpiresHeader:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasFarFutureExpiresHeader

    HttpHeaderHasEtag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ["setName", ["HttpHeaderHasEtag"]]
            - ["setHeaderToSearchFor", ["ETag"]]

    HttpHeaderResourceFound:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderStatusCode
        calls:
            - ["setValue", ["200"]]

    HttpHeaderNotModifiedOnIfModifiedSince:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderRespondsToIfModifiedSince

    HttpHeaderResourceIsMissing:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderStatusCode
        calls:
            - ["setValue", ["404"]]

    HttpHeaderResourceIsGzipped:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderResourceIsGzipped

    HttpHeaderContentTypeNoSniffing:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderIsPresentWithValue
        calls:
            - ["setName", ["HttpHeaderContentTypeNoSniffing"]]
            - ["setHeaderToSearchFor", ["X-Content-Type-Options"]]
            - ["setValue", ["nosniff"]]

    HttpHeaderFrameOptionsSameOrigin:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderFrameOptionsSameOrigin"]]
            - ["setHeaderToSearchFor", ["X-Frame-Options"]]
            - ["setValue", ["SAMEORIGIN"]]

    HttpHeaderCookieWithHttpOnlyFlag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderCookieWithHttpOnlyFlag"]]
            - ["setHeaderToSearchFor", ["Set-Cookie"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; HttpOnly"]]

    HttpHeaderCookieWithHttpSecureFlag:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderCookieWithHttpSecureFlag"]]
            - ["setHeaderToSearchFor", ["Set-Cookie"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; Secure"]]

    #Better use HttpHeaderHSTSWithSubdomains
    HttpHeaderHSTSPresent:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderPresent
        calls:
            - ["setName", ["HttpHeaderHSTSPresent"]]
            - ["setHeaderToSearchFor", ["Strict-Transport-Security"]]

    HttpHeaderHSTSWithSubdomains:
        class: \Frickelbruder\KickOff\Rules\HttpHeaderHasValue
        calls:
            - ["setName", ["HttpHeaderHSTSWithSubdomains"]]
            - ["setHeaderToSearchFor", ["Strict-Transport-Security"]]
            - ["setExactMatch", [false]]
            - ["setValue", ["; includeSubDomains"]]

    TitleTagLength:
        class: \Frickelbruder\KickOff\Rules\TitleTagLength

    MetaDescriptionLength:
        class: \Frickelbruder\KickOff\Rules\MetaDescriptionLength

    OGPropertyPresent:
        class: \Frickelbruder\KickOff\Rules\OgPropertyPresent

    TwitterProperty:
        class: \Frickelbruder\KickOff\Rules\TwitterProperty

    LinkRelCanonical:
        class: \Frickelbruder\KickOff\Rules\LinkRelCanonical

    LinkHrefLang:
        class: \Frickelbruder\KickOff\Rules\LinkHrefLang

    AppleTouchIcon:
        class: \Frickelbruder\KickOff\Rules\AppleTouchIcon

    MetaGeneratorNotPresent:
        class: \Frickelbruder\KickOff\Rules\MetaGeneratorNotPresent

    FindStringOnWebsite:
        class: \Frickelbruder\KickOff\Rules\FindStringOnWebsite
        calls:
            - ["setName", ["FindStringOnWebsite"]]
